//create
###
curl -X POST "http://localhost:3000/api/users" \
     -H "Content-Type: application/json" \
     -d '{
          "firstname": "Ahmad123",
          "lastname": "Ramdhani",
          "birthdate": "2000-05-15",
          "street": "Jl. Merdeka",
          "city": "Bandung",
          "province": "Jawa Barat",
          "postal_code": "40115"
        }'


//find by id
###
curl -X GET "http://localhost:3000/api/users/46"

//get all
###
curl -X GET "http://localhost:3000/api/users?page=1&limit=5"

//find by firstname
###
curl -X GET "http://localhost:3000/api/users/firstname/ahmad?page=1&limit=5"

// update
###
curl -X PUT "http://localhost:3000/api/users/42" \
     -H "Content-Type: application/json" \
    -d '{
          "firstname": "update",
          "lastname": "Ramdhani2123",
          "birthdate": "2000-05-15",
          "street": "Jl. Merdeka",
          "city": "Bandung",
          "province": "Jawa Barat",
          "postal_code": "40115"
        }'

//delete
###
curl -X DELETE "http://localhost:3000/api/users/45"

